version: '3.3'

volumes:
  static:
  media:
  postgres_data:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./.env

  backend:
    image: catiska/foodgram_backend:latest
    volumes:
      - static:/backend_static
      - media:/app/media/recipes
    env_file: ./.env
    depends_on:
      - db

  frontend:
    image: catiska/foodgram_frontend:latest
    env_file: ./.env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - ../frontend/:/app/result_build/
      - static:/frontend_static
      - media:/app/media/recipes
    depends_on:
      - db

  nginx:
    container_name: foodgram_gateway
    image: nginx:1.23.3-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles/
      - media:/app/media/recipes
    depends_on:
      - backend
      - frontend
