# Generated by Django 4.2.1 on 2023-06-17 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_squashed_0003_alter_recipe_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientsamount',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Нужно хоть какое-то количество ингредиента')], verbose_name='Количество'),
        ),
    ]
